#!/bin/bash
# This script goes in /usr/bin/pull-admit
# Requires curl to be installed, which should be done by the preseed configuration
set -e -u

SSH_DIR=/etc/ssh
CONFIG_DIR=/etc/hyades

SSHD_CONFIG=/usr/lib/hyades/sshd_config.for_admission
ADMISSION_CERT="${CONFIG_DIR}/admission.pem"
ADMISSION_TOKEN="$1"
source "${CONFIG_DIR}/admission.conf" # just for ADMISSION_SERVER

KEYTYPES="ecdsa ed25519 rsa"

echo "Admitting..."

mkdir -p "${CONFIG_DIR}"

function admit_req() {
	if [ "${3:-}" != "" ]
	then
		curl --data-binary "@${3}" -H "X-Bootstrap-Token: ${ADMISSION_TOKEN}" --cacert "${ADMISSION_CERT}" "https://${ADMISSION_SERVER}:2557/${1}" >"${2}"
	else
		curl -H "X-Bootstrap-Token: ${ADMISSION_TOKEN}" --cacert "${ADMISSION_CERT}" "https://${ADMISSION_SERVER}:2557/${1}" >"${2}"
	fi
}

admit_req "config/cluster.conf" "${CONFIG_DIR}/cluster.conf"
admit_req "config/local.conf" "${CONFIG_DIR}/local.conf"
admit_req "config/ssh_user_ca.pub" "${SSH_DIR}/ssh_user_ca.pub"

PUBKEYS_PACKED="${SSH_DIR}/pubkeys_packed.tmp"
CERTS_PACKED="${SSH_DIR}/certs_packed.tmp"

(for type in ${KEYTYPES}; do cat "${SSH_DIR}/ssh_host_${type}_key.pub"; done) >"${PUBKEYS_PACKED}"

if [ "$(wc -l <"${PUBKEYS_PACKED}")" != 3 ]
then
	echo "Unexpected number of pubkeys" 1>&2
	exit 1
fi

admit_req "certificates" "${CERTS_PACKED}" "${PUBKEYS_PACKED}"

if [ "$(wc -l <"${CERTS_PACKED}")" != 3 ]
then
	echo "Unexpected number of certs" 1>&2
	exit 1
fi

(for type in ${KEYTYPES}; do head -n 1 >"${SSH_DIR}/ssh_host_${type}_cert"; done) <"${CERTS_PACKED}"

rm -f "${PUBKEYS_PACKED}" "${CERTS_PACKED}"

cp -f "${SSHD_CONFIG}" "${SSH_DIR}/sshd_config.admit"
mv "${SSH_DIR}/sshd_config" "${SSH_DIR}/sshd_config.before_admit"
mv "${SSH_DIR}/sshd_config.admit" "${SSH_DIR}/sshd_config"

systemctl restart ssh

echo "Admitted!"
