#!/bin/sh
# postrm script for homeworld-authserver
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        sed -i -E "s/^#(session .+ pam_motd.so .+)$/\1/g" /etc/pam.d/sshd
        mv /etc/ssh/sshd_config /etc/ssh/sshd_config.rmtmp
        dpkg-divert --remove --package hyades-authserver --rename /etc/ssh/sshd_config
        if [ ! -e /etc/ssh/sshd_config ]
        then
            mv /etc/ssh/sshd_config.rmtmp /etc/ssh/sshd_config
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
