#!/bin/sh
# postinst script for homeworld-authserver
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure|abort-remove)
        cp -f /etc/ssh/sshd_config.hyades-new /etc/ssh/sshd_config
        adduser --system --shell /usr/bin/hyauth kauth
        touch /home/kauth/.k5login
        touch /root/.k5login
        sed -i -E "s/^(session .+ pam_motd.so .+)$/#\1/g" /etc/pam.d/sshd
    ;;

    abort-upgrade|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
