#!/bin/bash
set -e
ssh -TKk kauth@egg-sandwich.mit.edu <~/.ssh/id_rsa.pub >~/.ssh/id_rsa-cert.pub.tmp || (echo "Failed to request new certificate." && false)
if [ -s ~/.ssh/id_rsa-cert.pub.tmp ]
then
	mv ~/.ssh/id_rsa-cert.pub.tmp ~/.ssh/id_rsa-cert.pub
	echo "Certificate updated." 1>&2
	ssh-keygen -L -f ~/.ssh/id_rsa-cert.pub
else
	rm -f ~/.ssh/id_rsa-cert.pub.tmp
	echo "Failed to get new certificate." 1>&2
	exit 1
fi
