load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# TODO: audit all downloads, make sure they're all source code
# old version used for go1.9.3 support
http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.14.7/rules_go-0.14.7.tar.gz"],
    sha256 = "1a5b8d49a052127af0d444c8e9711a120dd50e373a8da88714fdda46e11f7a90",
)

http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.15.0/bazel-gazelle-0.15.0.tar.gz"],
    sha256 = "6e875ab4b6bf64a38c352887760f21203ab054676d9c1b274963907e0768740d",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

# TODO: stop using binaries built by upstream; use our own
go_register_toolchains(
    # TODO: bump this to 1.10+, so that we can stop using an old version of rules_go!
    go_version = "1.9.3",
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
load("//bazel:gorepo_patchfix.bzl", "go_repository_alt")

gazelle_dependencies()

# kube-state-metrics

go_repository_alt(
    name = "com_github_kubernetes_kube_state_metrics",
    commit = "5ccda14bbff25a1007e13dfc3a75e5bb998abe6d",           # v1.2.0
    importpath = "k8s.io/kube-state-metrics",
    prepatch_cmds = ["find vendor/k8s.io -name BUILD -delete"],    # because the vendored kubernetes comes with BUILD files that will break the generated BUILDs:
    postpatches = ["//kube-state-metrics:state-visibility.patch"], # so that we can compile our own kube-state-metrics binary with our own options:
)
