#!/usr/bin/env bash

set -e -u

BINARYDIR=${BINARYDIR:-bin}
BUILDDIR=${BUILDDIR:-bin}

ACBUILD=${ACBUILD:-acbuild}

VERSION=$1

if ! command -v $ACBUILD >/dev/null; then
    echo "acbuild ($ACBUILD) is not executable"
    exit 1
fi

if [ ! -x $BINARYDIR/etcd ] ; then
    echo "$BINARYDIR/etcd not found. Is it compiled?"
    exit 1
fi

if [ -z "$VERSION" ] ; then
    echo "Usage: scripts/build-aci VERSION"
    exit 1
fi

acbuild --debug begin

acbuildEnd() {
    EXIT=$?
    acbuild --debug end && exit $EXIT
}
trap acbuildEnd EXIT

acbuild --debug set-name hyades.mit.edu/etcd

acbuild --debug copy $BINARYDIR/etcd /usr/local/bin/etcd

acbuild --debug environment add ETCD_DATA_DIR /var/lib/etcd
acbuild --debug mount add data-dir /var/lib/etcd

acbuild --debug label add version "$VERSION"

acbuild --debug set-exec -- /usr/local/bin/etcd

acbuild --debug port add client tcp 2379
acbuild --debug port add peer tcp 2380

acbuild --debug copy local-hosts /etc/hosts

# mkdir default data-dir
mkdir -p .acbuild/currentaci/rootfs/var/lib/etcd

GENPATH="$(realpath $BUILDDIR/etcd-${VERSION}-linux-amd64.aci)"

acbuild --debug write --overwrite "${GENPATH}"

THIS="$(realpath $0)"
TMEXT="$(realpath $BUILDDIR/temp-extract)"

trap - EXIT
acbuild --debug end

rm -rf "${TMEXT}"
mkdir "${TMEXT}"
cd "${TMEXT}"
tar -xzf "${GENPATH}"
touch -r "${THIS}" --no-create $(find)
rm "${GENPATH}"
tar -cf "${GENPATH}.tar" .
gzip -n "${GENPATH}.tar"
mv "${GENPATH}.tar.gz" "${GENPATH}"
