#!/usr/bin/env bash

set -e -u

BINARYDIR=${BINARYDIR:-bin}
BUILDDIR=${BUILDDIR:-bin}

ACBUILD=${ACBUILD:-acbuild}

VERSION=$1

if ! command -v $ACBUILD >/dev/null; then
    echo "acbuild ($ACBUILD) is not executable"
    exit 1
fi

if [ ! -x $BINARYDIR/flanneld ] ; then
    echo "$BINARYDIR/flanneld not found. Is it compiled?"
    exit 1
fi

if [ -z "$VERSION" ] ; then
    echo "Usage: scripts/build-aci VERSION"
    exit 1
fi

acbuild --debug begin

acbuildEnd() {
    EXIT=$?
    acbuild --debug end && exit $EXIT
}
trap acbuildEnd EXIT

acbuild --debug set-name hyades.mit.edu/flannel

acbuild --debug copy $BINARYDIR/flanneld /usr/bin/flanneld
acbuild --debug copy $BINARYDIR/lib /lib/
acbuild --debug copy $BINARYDIR/lib64 /lib64/

acbuild --debug label add version "$VERSION"

acbuild --debug set-exec -- /usr/bin/flanneld

GENPATH="$(realpath $BUILDDIR/flannel-${VERSION}-linux-amd64.aci)"

acbuild --debug write --overwrite "${GENPATH}"

THIS="$(realpath $0)"
TMEXT="$(realpath $BUILDDIR/temp-extract)"

trap - EXIT
acbuild --debug end

rm -rf "${TMEXT}"
mkdir "${TMEXT}"
cd "${TMEXT}"
tar -xzf "${GENPATH}"
touch -r "${THIS}" --no-create $(find)
rm "${GENPATH}"
tar -cf "${GENPATH}.tar" .
gzip -n "${GENPATH}.tar"
mv "${GENPATH}.tar.gz" "${GENPATH}"
