#!/bin/sh
set -e

case "$1" in
    remove)
        # TODO: autogenerate this
        systemctl stop aci-pull-monitor.service apiserver.service etcd.service etcd-metrics-exporter.service homeworld-autostart.service kube-ctrlmgr.service kubelet.service kube-proxy.service kube-scheduler.service kube-state-metrics.service setup-queue.timer setup-queue.service
    ;;

    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
